# Generated by Django 5.0.4 on 2024-04-26 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auction', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='users.tguser', verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='auction',
            name='betters',
            field=models.ManyToManyField(related_name='auctions', through='auction.Bet', to='users.tguser', verbose_name='Поставившие ставку'),
        ),
        migrations.AddField(
            model_name='auction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='auction.product', verbose_name='Товар'),
        ),
    ]
