# Generated by Django 5.0.4 on 2024-05-04 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_user_penalties_and_auction_fixes'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Заблокирован ли'),
        ),
        migrations.AddField(
            model_name='tguser',
            name='warning_count',
            field=models.IntegerField(default=0, verbose_name='Количество предупреждений'),
        ),
        migrations.AlterField(
            model_name='bettransaction',
            name='bet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='auction.bet', verbose_name='Ставка'),
        ),
    ]
